services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet_user -d wallet_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
